### ISSUE TITLE
Can't find the pretrained model download link

### ISSUE THREAD

**Issue by coordxyz** [amazon-science/patchcore-inspection#36]
Hi, does anyone know that where can I download the pretrained PatchCore model? Thx~
It seems that the 'add link' mentioned in Readme is not available.
"A set of pretrained PatchCores are hosted here: **__add link__**. To use them (and replicate training),
check out `sample_evaluation.sh` and `sample_training.sh`."

**Comment by ZS-YANG** [comment]
Have you solved this problem

**Comment by hjs2027864933** [comment]
> Have you solved this problem

Can't seem to see the hostet link

**Comment by dianaartiom** [comment]
Hi, thanks for your contribution to the open source community. When can we access the pretrained models link?

Thank you in advance. 🙏

**Comment by petergehler** [comment]
I have just downloaded the pretrained models to `models/` via git lfs. Sorry it took so long.

**Comment by onkarkris** [comment]
> I have just downloaded the pretrained models to `models/` via git lfs. Sorry it took so long.

But the pickle file in the pretrained model folder seems corrupted. They are showing "KeyError: 'v'" How to solve this?

**Comment by ybai111** [comment]
> 

have you solved this？

**Comment by gagapaga** [comment]
have you solved this issue?
