### ISSUE TITLE
(Resolved)VallueError: Found input variables with inconsistent numbers of samples [xxx,yyy]

### ISSUE THREAD

**Issue by TheWangYang** [amazon-science/patchcore-inspection#47]
#### I finally solved the problem and the analysis is as follows:
* When training my model input parameters are set as follows: --resize 256 --imagesize 244;
* But when I loaded the pre-trained model, I set the model input parameters as follows: --resize 366 --imagesize 320;
* The reason is that when training and evaluating the same model, the image input sizes are not consistent;
* Finally, modify the input parameters of the evaluation model to those input during model training;

**Comment by lekshmijk** [comment]
thank youuu!!!

**Comment by lekshmijk** [comment]
thank you!!

**Comment by TheWangYang** [comment]
> thank you!!

It doesn't matter. Easy.
