### ISSUE TITLE
Pre Trained Weights 

### ISSUE THREAD

**Issue by RizwanAliQau** [amazon-science/patchcore-inspection#48]
Kindly someone provides the pretrained weights. As they put the link option but still not provides the weights.

**Comment by petergehler** [comment]
Thanks for the request. We have not released the weights yet but it is planned with no timeline unfortunately. I will leave this open and comment once uploaded.

**Comment by RizwanAliQau** [comment]
thank you, looking forward to getting the update soon.

**Comment by petergehler** [comment]
I just uploaded the models to the `models/` folder via lfs.

**Comment by RizwanAliQau** [comment]
thank you so much, I really appreciate that
